### ISSUE TITLE
USB serial adapter specification

### ISSUE THREAD

**Issue by ea2973929** [johellstrand/rego637_v304#1]
Is there a link to the Husdata USB-serial adapter used? 

Is there anything special with it or could any USB - serial work?

**Comment by johellstrand** [comment]
Följande skrev Peter Hansson på husdata att jag skulle skriva på beställningen av H10 interfacet:
Övrigt: 700 kronors H10 interface.

"Ett sådant interface säljer vi normalt för 600kr men då du vill ansluta till RPI behöver du en annan USB sladd som har annat chip så det blir en hundring dyrare

Beställ H10 och skriv att du endast ska ha interface för 700kr så justerar vi fakturan.
"
